# Generated by Django 2.2.24 on 2021-06-15 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='category',
            name='uploaded',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
    ]
