# Generated by Django 2.2.24 on 2021-06-15 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210616_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='updated',
            new_name='uploaded',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
