# Generated by Django 2.2.24 on 2021-06-16 02:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210616_0538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='product/%Y/%m/%d', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
