# Generated by Django 2.2.24 on 2021-06-16 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210616_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='product/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(upload_to='category/', verbose_name='Изображение'),
        ),
    ]
