# Generated by Django 2.2.24 on 2021-06-17 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210617_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Полное описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Красткое описание'),
        ),
    ]
